sudo: required

language: python

services: 
  - docker

notifications:
    email:
        on_success: never
        on_failure: always

addons:
    apt:
        packages:
            - curl
            - openssh-client

install:
    - docker build -t aiida-prerequisites .
    - mkdir tmp
    - export DOCKERID=`docker run -v $PWD/tmp:/home/aiida -d aiida-prerequisites`
    - docker exec --tty --user root $DOCKERID wait-for-services
    - docker exec --tty --user aiida $DOCKERID wait-for-services

script:
    - "echo \"Docker ID: $DOCKERID\""
    - docker exec --tty --user aiida $DOCKERID /bin/bash -l -c '/usr/lib/postgresql/10/bin/pg_ctl -D /home/$SYSTEM_USER/.postgresql status' # Checking that postgres is up.
    - docker exec --tty --user root $DOCKERID /bin/bash -l -c 'service rabbitmq-server status' # Checking that rabbitmq is up.
    - sudo cp tmp/.ssh/id_rsa . # Copying id_rsa file from the mounted folder.
    - docker stop $DOCKERID # Stopping the container.
    - export DOCKERID=`docker run -v $PWD/tmp:/home/aiida -d aiida-prerequisites` # Starting container using the same mounted folder.
    - docker exec --tty $DOCKERID wait-for-services
    - sudo diff id_rsa tmp/.ssh/id_rsa  # Checking that the id_rsa file wasn't modified.
