sudo: required

language: python

services: 
  - docker

notifications:
    email:
        on_success: never
        on_failure: always

addons:
    apt:
        packages:
            - curl
            - openssh-client

install:
    - docker build -t aiida-prerequisites .
    - docker run -d aiida-prerequisites
    - "export DOCKERID=`docker ps -qf 'ancestor=aiida-prerequisites'`"
    - while [[ \"healthy\" != `docker inspect --format='{{json .State.Health.Status}}' $DOCKERID` ]]; do sleep 1; done

# Check that PostgreSQL and RabbitMQ are up.
script:
    - "echo \"Docker ID: $DOCKERID\""
    - "docker exec --tty --user aiida \"$DOCKERID\" /bin/bash -l -c '/usr/lib/postgresql/10/bin/pg_ctl -D /home/$SYSTEM_USER/.postgresql status'" # checking postgres
    - "docker exec --tty --user root \"$DOCKERID\" /bin/bash -l -c 'service rabbitmq-server status'" # checking rabbitmq
