sudo: required

language: python

services: 
  - docker

notifications:
    email:
        on_success: never
        on_failure: always

addons:
    apt:
        packages:
            - curl
            - openssh-client

install:
    - docker build -t aiida-prerequisites .
    - mkdir tmp
    - export DOCKERID=`run -v $PWD/tmp:/home/aiida -d aiida-prerequisites`
    - docker exec --tty --user root $DOCKERID wait-for-services
    - docker exec --tty --user aiida $DOCKERID wait-for-services

# Check that PostgreSQL and RabbitMQ are up.
script:
    - echo "Docker ID: $DOCKERID"
    - docker exec --tty --user aiida $DOCKERID /bin/bash -l -c '/usr/lib/postgresql/10/bin/pg_ctl -D /home/$SYSTEM_USER/.postgresql status' # checking postgres
    - docker exec --tty --user root $DOCKERID /bin/bash -l -c 'service rabbitmq-server status' # checking rabbitmq
    - cp tmp/.ssh/id_rsa . # copying id_rsa file from the mounted folder
    - docker stop $DOCKERID # stopping the container
    - export DOCKERID=`run -v $PWD/tmp:/home/aiida -d aiida-prerequisites`
    - docker exec --tty $DOCKERID wait-for-services
    - diff id_rsa tmp/.ssh/id_rsa  # checking that the id_rsa file wasn't modified
