# Execute continuous integration tests for this docker image. This is to ensure that
# new versions of the image do not break currently expected behavior and that the
# environment provided by this image is compatible with a selected set of apps.

name: build-and-push-to-dockerhub

on:
  push:
    branches:
      - switch-to-github-actions
    tags:
      - '*'

jobs:

  build-docker-image:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    outputs:
      tag: ${{ steps.setup.outputs.tag }}

    steps:
      -
        uses: actions/checkout@v2
      - 
        name: Extract branch name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/*/})"
        id: extract_branch
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository }}:${{ steps.extract_branch.outputs.tag }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
